### ISSUE TITLE
Need to refresh MO2 modlist after file changes.

### ISSUE THREAD

**Issue by mdavis199** [mihaifm/broom#1]
If one of the files being hidden or deleted is a plugin, MO2's mod list must be updated. Otherwise other tools, like Loot and Loot Warning Checker, will throw errors when expected plugins are not found.

It can be fixed by changing this section of `fileSignalHandler()`

https://github.com/mihaifm/broom/blob/786e81ac3380ffd318f2e13fd727cde291da54ba/mo2/Broom.py#L266

to this:

```python
self.cleanButton.setEnabled(False)

if len(self.__matchedFiles):
    self.__organizer.refreshModList()

```

Thanks for sharing your work.  Loving this plugin.  It's definitely underrated.

**Comment by mihaifm** [comment]
Thanks, that sounds like a good suggestion. I’ll try it out and make the change

**Comment by mihaifm** [comment]
Released a new version which includes this fix, thanks a lot.
