### ISSUE TITLE
Suggestion: Allow comments

### ISSUE THREAD

**Issue by mdavis199** [mihaifm/broom#2]
It'd be great if we could include comments in the broom files so that we can remember why we hide a file.

Any way you would filter the rules list to remove lines starting with '#'?

This changed is what worked for me.

https://github.com/mihaifm/broom/blob/786e81ac3380ffd318f2e13fd727cde291da54ba/mo2/Broom.py#L111-L116

Changed to this
```python
globalRules = "\n".join(
    filter(
        lambda x: len(x) > 0,
        map(lambda x: x.strip(), [l for l in globalRules.splitlines() if not l.startswith('#')]),
    )
)

```

**Comment by mihaifm** [comment]
Yea the file format can be expanded a little bit. Thanks for the suggestion, this looks reasonable.

**Comment by mihaifm** [comment]
Comments are now supported in the latest release,

It took some time to release a new version, but I also added a feature to negate rules with "!", similar to what gitignore does. 

Thanks for the help again.
